### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by a3020** [a3020/marketplace_sales#1]
Must haves
- [x] Make it possible to parse an email to a sale
- [x] Show list of sales
- [x] Show total amount
- [ ] Make it possible to add two or more 'sales' to an order (e.g. two emails can be sent with an identical order number)
- [ ] Make it possible to edit an order
- [ ] Keep track of refunds
- [ ] Allow bulk importing emails

Would haves:
- [x] Datatable for sales overview
- [ ] Manually adding orders
- [ ] Graphs
